controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

car_new:
    path: /car/new
    controller: App\Controller\CarController::create
    methods: [POST]
