# config/services.yaml
parameters:
    upload_directory: '%kernel.project_dir%/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # Manually define the User entity as a service
    App\Entity\User:
        arguments: []
        public: true