<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxYLNIi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxYLNIi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxYLNIi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxYLNIi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxYLNIi\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxYLNIi',
    'container.build_id' => '89905d66',
    'container.build_time' => 1713829647,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxYLNIi');
