<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxoJcgA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxoJcgA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAxoJcgA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAxoJcgA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAxoJcgA\App_KernelDevDebugContainer([
    'container.build_hash' => 'AxoJcgA',
    'container.build_id' => '6ea96e91',
    'container.build_time' => 1714003234,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxoJcgA');
