<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBMMfz8v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBMMfz8v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBMMfz8v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBMMfz8v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBMMfz8v\App_KernelDevDebugContainer([
    'container.build_hash' => 'BMMfz8v',
    'container.build_id' => 'ffaaa708',
    'container.build_time' => 1714167758,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBMMfz8v');
