<?php

namespace ContainerXHJsovM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveExpiredSubscriptionsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RemoveExpiredSubscriptionsCommand' shared autowired service.
     *
     * @return \App\Command\RemoveExpiredSubscriptionsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'RemoveExpiredSubscriptionsCommand.php';

        $container->privates['App\\Command\\RemoveExpiredSubscriptionsCommand'] = $instance = new \App\Command\RemoveExpiredSubscriptionsCommand(($container->privates['App\\Repository\\SubscriptionRepository'] ?? $container->load('getSubscriptionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:remove-expired-subscriptions');
        $instance->setDescription('Removes expired subscriptions from the database.');

        return $instance;
    }
}
