<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Car extends \App\Entity\Car implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abs' => [parent::class, 'abs', null],
        "\0".parent::class."\0".'addDate' => [parent::class, 'addDate', null],
        "\0".parent::class."\0".'autoGearBox' => [parent::class, 'autoGearBox', null],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'epc' => [parent::class, 'epc', null],
        "\0".parent::class."\0".'grayCard' => [parent::class, 'grayCard', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'insurance' => [parent::class, 'insurance', null],
        "\0".parent::class."\0".'mark' => [parent::class, 'mark', null],
        "\0".parent::class."\0".'mileage' => [parent::class, 'mileage', null],
        "\0".parent::class."\0".'model' => [parent::class, 'model', null],
        "\0".parent::class."\0".'pictures' => [parent::class, 'pictures', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null],
        "\0".parent::class."\0".'sellDate' => [parent::class, 'sellDate', null],
        "\0".parent::class."\0".'taxes' => [parent::class, 'taxes', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'abs' => [parent::class, 'abs', null],
        'addDate' => [parent::class, 'addDate', null],
        'autoGearBox' => [parent::class, 'autoGearBox', null],
        'color' => [parent::class, 'color', null],
        'description' => [parent::class, 'description', null],
        'epc' => [parent::class, 'epc', null],
        'grayCard' => [parent::class, 'grayCard', null],
        'id' => [parent::class, 'id', null],
        'insurance' => [parent::class, 'insurance', null],
        'mark' => [parent::class, 'mark', null],
        'mileage' => [parent::class, 'mileage', null],
        'model' => [parent::class, 'model', null],
        'pictures' => [parent::class, 'pictures', null],
        'price' => [parent::class, 'price', null],
        'quantity' => [parent::class, 'quantity', null],
        'sellDate' => [parent::class, 'sellDate', null],
        'taxes' => [parent::class, 'taxes', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
