<?php

namespace ContainerVAFAyIG;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mb8qaJ5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mb8qaJ5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mb8qaJ5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'message' => ['privates', '.errored..service_locator.mb8qaJ5.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.mb8qaJ5": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'message' => 'App\\Entity\\Message',
        ]);
    }
}
